### ISSUE TITLE
Unable to run MUI (as need to update version of V)

### ISSUE THREAD

**Issue by Wajinn** [malisipi/mui#19]
It might be good to show what version of V that MUI is using, and to clarify what version of OSes tested on.  I had the problem a couple of times before, where MUI examples would not run, because of using an older version of V.  So after updating, they work.  Additionally, V's upgrade can be a bit finicky, where it can be better to remove and then re-install.

Additionally, if only Windows 11 is targeted, then it might not work on Windows 8.1/10.  The majority of Windows users, can still be on Windows 10.  For example: Windows 10 at 70%, Windows 11 around 15%, and Windows 8.1 and Windows 7 still at over 10%.  A UI that works on say only 20% of the user systems, would obviously be problematic.  Not everyone is going to quickly upgrade to the latest and newest of something, be it the latest version of V or the latest version of an OS.

**Comment by malisipi** [comment]
> It might be good to show what version of V that MUI is using, and to clarify what version of OSes tested on. 

I am using latest V to test it. And I am testing MUI on Windows 11, Arch Linux, Android 12 and Wine 8.1. Until i have a problem with Virtualitation Software, I was tested it with also Windows 7. When I fix it, i will test it again. 

> I had the problem a couple of times before, where MUI examples would not run, because of using an older version of V. So after updating, they work. Additionally, V's upgrade can be a bit finicky, where it can be better to remove and then re-install.

I have faced with the issue. But after updating V and that fixed automatically the issue, I was think this is a compiler-bug that fixed in latest V. And I ignore it.

Also sometimes latest-V can broke entire codebase and i need to broke the support to have compability with latest-V. It was happened in `sum types` update and similar updates.

> Additionally, if only Windows 11 is targeted, then it might not work on Windows 8.1/10. 

Only UI theme is the part is especially designed for Windows 11. It should be work on old windows and other OS if enabled.

> A UI that works on say only 20% of the user systems, would obviously be problematic. Not everyone is going to quickly upgrade to the latest and newest of something, be it the latest version of V or the latest version of an OS.

I agree but testing a lot OS and supporting V/Vlib changes is making harder on old-V compatible. Nevertheless I want to make compatible as possible.

If you have issue with old OS or V-version, please let me know specific information about the OS and V version. If i can make MUI compatible with that, i will do it.

Thanks for your attention.
